const data = [
    {
        bloque: 'c',
        nivel: '1',
        fila: '1',
        columna: '3',
        numero_tanque: null,
    },
    {
        bloque: 'c',
        nivel: '1',
        fila: '2',
        columna: '3',
        numero_tanque: null,
    },
    {
        bloque: 'c',
        nivel: '1',
        fila: '3',
        columna: '3',
        numero_tanque: null,
    },
    {
        bloque: 'c',
        nivel: '1',
        fila: '4',
        columna: '3',
        numero_tanque: null,
    },
    {
        bloque: 'c',
        nivel: '1',
        fila: '5',
        columna: '3',
        numero_tanque: null,
    },
    {
        bloque: 'c',
        nivel: '1',
        fila: '6',
        columna: '3',
        numero_tanque: null,
    },
    {
        bloque: 'c',
        nivel: '2',
        fila: '1',
        columna: '3',
        numero_tanque: null,
    },
    {
        bloque: 'c',
        nivel: '2',
        fila: '2',
        columna: '3',
        numero_tanque: null,
    },
    {
        bloque: 'c',
        nivel: '2',
        fila: '3',
        columna: '3',
        numero_tanque: null,
    },
    {
        bloque: 'c',
        nivel: '2',
        fila: '4',
        columna: '3',
        numero_tanque: null,
    },
    {
        bloque: 'c',
        nivel: '2',
        fila: '5',
        columna: '3',
        numero_tanque: null,
    },
    {
        bloque: 'c',
        nivel: '2',
        fila: '6',
        columna: '3',
        numero_tanque: null,
    },
   
]